channels:
- conda-forge
dependencies:
- python=3.12.7
- pip<=25.0.1
- pip:
  - mlflow==2.22.1
  - cloudpickle==3.1.1
  - numpy==2.3.0
  - pandas==2.2.3
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - dagshub==0.5.10
  - seaborn==0.13.2
  - matplotlib==3.10.3
  - google-api-python-client==2.172.0
  - google-auth-httplib2==0.2.0
  - google-auth-oauthlib==1.2.2
  - joblib==1.5.1
name: mlflow-env